"""
src/core/enums.py

Enumerations for the Adaptive-IPI project.

All categorical values used across the codebase are defined here.
This eliminates magic strings and ensures consistency across modules.
"""

from enum import Enum


class Label(int, Enum):
    """Binary classification labels for IPI detection."""

    BENIGN = 0
    ATTACK = 1


class Split(str, Enum):
    """Dataset split identifiers."""

    TRAIN = "train"
    VALIDATION = "validation"
    TEST = "test"


class AttackType(str, Enum):
    """Types of attacks in the dataset.

    These correspond to the attack categorizations used in BIPIA.
    Additional types may be added for teacher-generated hard negatives.
    """

    BENIGN = "benign"
    INDIRECT_PROMPT_INJECTION = "indirect_prompt_injection"
    # Hard-negative types (generated by teacher in Phase 5)
    HARD_NEGATIVE_GENERATED = "hard_negative_generated"


class ContextType(str, Enum):
    """Context types from the BIPIA benchmark.

    Each type represents a different application scenario
    in which indirect prompt injection may occur.
    """

    EMAIL = "email"
    QA = "qa"
    ABSTRACT = "abstract"
    TABLE = "table"
    CODE = "code"
    # For generated examples that don't map to a specific BIPIA task
    SYNTHETIC = "synthetic"


class TeacherBackend(str, Enum):
    """Supported teacher model inference backends."""

    VLLM = "vllm"
    TRANSFORMERS = "transformers"
    API = "api"


class Phase(str, Enum):
    """Pipeline phase identifiers."""

    PREPROCESS = "phase1_preprocess"
    TEACHER_ANNOTATE = "phase2_teacher"
    INITIAL_DISTILL = "phase3_distill"
    FAILURE_ANALYSIS = "phase4_analyze"
    HARD_NEG_GENERATE = "phase5_generate"
    RETRAIN = "phase6_retrain"
    EVALUATE = "phase7_evaluate"
